language: bash

sudo: required

services:
  - docker

matrix:
  fast_finish: true

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

addons:
  apt:
    packages:
      - p7zip-full

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
  - tar xf shellcheck-latest.linux.x86_64.tar.xz
  - ./shellcheck-latest/shellcheck --version
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker

script:
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck install.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/7zcat'
  - bash .travis/script.sh
  - ./perfecto-docker 7zcat.spec
