language: bash

sudo: false

addons:
  apt:
    packages:
      - p7zip-full

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
  - tar xf shellcheck-latest.linux.x86_64.tar.xz

script:
  - bash -c 'shopt -s globstar; ./shellcheck/shellcheck SOURCES/7zcat'
  - bash .travis/script.sh

matrix:
  fast_finish: true
