language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - p7zip-full
      - shellcheck

script:
  - bash -c 'shopt -s globstar; shellcheck SOURCES/7zcat'
  - bash .travis/script.sh

matrix:
  fast_finish: true
