#!/usr/bin/env bash
# shellcheck disable=SC1117,SC2034,SC2154

########################################################################################

if [[ -n "${SCRIPT_DEBUG}" ]] ; then
  set -x
fi

########################################################################################

APP="7zcat"
VER="1.3.5"

########################################################################################

NORM=0
BOLD=1
UNLN=4
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[0m"
CL_BOLD="\e[0;${BOLD};49m"
CL_UNLN="\e[0;${UNLN};49m"
CL_RED="\e[0;${RED};49m"
CL_GREEN="\e[0;${GREEN};49m"
CL_YELLOW="\e[0;${YELLOW};49m"
CL_BLUE="\e[0;${BLUE};49m"
CL_MAG="\e[0;${MAG};49m"
CL_CYAN="\e[0;${CYAN};49m"
CL_GREY="\e[0;${GREY};49m"
CL_DARK="\e[0;${DARK};49m"
CL_BL_RED="\e[1;${RED};49m"
CL_BL_GREEN="\e[1;${GREEN};49m"
CL_BL_YELLOW="\e[1;${YELLOW};49m"
CL_BL_BLUE="\e[1;${BLUE};49m"
CL_BL_MAG="\e[1;${MAG};49m"
CL_BL_CYAN="\e[1;${CYAN};49m"
CL_BL_GREY="\e[1;${GREY};49m"

########################################################################################

SUPPORTED_ARGS="pass password !fast !no_colors !help !usage !version !ver"
SHORT_ARGS="p:password F:!fast nc:!no_colors h:!help v:!version"

########################################################################################

main() {
  if [[ ! -t 1 || -n "$no_colors" ]] ; then
    unset NORM BOLD UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_BL_DARK
  fi

  if [[ -n "$ver" || -n "$version" ]] ; then
    about
    exit 0
  fi

  if [[ -n "$help" || -n "$usage" || $# -eq 0 ]] ; then
    usage
    exit 0
  fi

  if ! type -P 7za &>/dev/null ; then
    error "Error! 7zip not installed." $RED
    exit 1
  fi

  [[ -n "$pass" ]] && password="$pass"
  [[ "$password" == "true" ]] && readUserPassword

  local file file_name has_errors options

  options="-so -bd"

  if [[ -z "$fast" ]] ; then
    options="-mmt1 $options"
  fi

  for file in "$@" ; do
    file_name=$(basename "$file")

    if [[ ! -f $file ]] ; then
      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a file." $RED
      continue
    elif [[ ! -r $file ]]; then
      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a readable file." $RED
      continue
    fi

    if ! is7zArch "$file" ; then
      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a 7z archive." $RED
      continue
    fi

    if isProtectedArch "$file" && [[ -z "$password" ]] ; then
      readUserPassword "$file"
    fi

    if [[ -n "$password" ]] ; then
      # shellcheck disable=SC2086
      7za e -p"${password}" $options "$file" 2> /dev/null

      if [[ $? -eq 2 ]] ; then
        error "Error! Wrong password." $RED
        has_errors=true
      fi
    else
      # shellcheck disable=SC2086
      7za e $options "$file" 2> /dev/null
    fi
  done

  if [[ -n "$has_errors" ]] ; then
    exit 1
  fi
}

# Read password
#
# 1: Path to file (String)
#
# Code: No
# Echo: No
readUserPassword() {
  local file_name

  file_name=$(basename "$1")

  while : ; do
    if [[ -n "$file_name" ]] ; then
      show "Please enter password for $file_name:" $CYAN
    else
      show "Please enter password:" $CYAN
    fi

    read -re -p "> " user_pass

    clnPassInput ${#user_pass}

    show ""

    if [[ -z "$user_pass" ]] ; then
      error "Password can't be empty" $YELLOW
    else
      password="$user_pass"
      break
    fi
  done
}

# Check if given file is 7z archive
#
# 1: Path to file (String)
#
# Code: Yes
# Echo: No
is7zArch() {
  7za l "$1" &> /dev/null
  return $?
}

# Check if archive use password protection
#
# 1: Path to file (String)
#
# Code: Yes
# Echo: No
isProtectedArch() {
  if [[ $(7za l "$1" | grep "7zAES") != "" ]] ; then
    return 0
  else
    return 1
  fi
}

# Replace entered password by masking symbols
#
# Code: No
# Echo: No
clnPassInput() {
  local i result

  result="${result}> "

  for i in $(seq 1 "$1") ; do
    result="${result}*"
  done

  printf "\e[1A%s\n" "$result"
}

########################################################################################

# Show message
#
# 1: Message (String)
# 2: Message color (Number) [Optional]
#
# Code: No
# Echo: No
show() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

# Print error message
#
# 1: Message (String)
# 2: Message color (Number) [Optional]
#
# Code: No
# Echo: No
error() {
  show "$@" 1>&2
}

# Print usage info
#
# Code: No
# Echo: No
usage() {
  show ""
  show "${CL_BOLD}Usage:${CL_NORM} 7zcat ${CL_GREEN}{options}${CL_NORM} file..."
  show ""
  show "Options" $BOLD
  show ""
  if [[ -n "$DARK" ]] ; then
    show "  ${CL_GREEN}--password, -p${CL_NORM} ${CL_GREY}password${CL_NORM} ${CL_DARK}..${CL_NORM} Use password for unpacking archives"
    show "  ${CL_GREEN}--fast, -F${CL_NORM} ${CL_DARK}...............${CL_NORM} Use all CPUs for unpacking data"
    show "  ${CL_GREEN}--no-color, -nc${CL_NORM} ${CL_DARK}..........${CL_NORM} Disable colors in output"
    show "  ${CL_GREEN}--help, -h${CL_NORM} ${CL_DARK}...............${CL_NORM} Show this help message"
    show "  ${CL_GREEN}--version, -v${CL_NORM} ${CL_DARK}............${CL_NORM} Show information about version"
  else
    show "  ${CL_GREEN}--password, -p${CL_NORM} ${CL_GREY}password${CL_NORM}    Use password for unpacking archives"
    show "  ${CL_GREEN}--fast, -F${CL_NORM}                 Use all CPUs for unpacking data"
    show "  ${CL_GREEN}--no-color, -nc${CL_NORM}            Disable colors in output"
    show "  ${CL_GREEN}--help, -h${CL_NORM}                 Show this help message"
    show "  ${CL_GREEN}--version, -v${CL_NORM}              Show information about version"
  fi
  show ""
  show "Examples" $BOLD
  show ""
  show "  7zcat file.7z"
  show "  Show content of file.7z" $DARK
  show ""
  show "  7zcat -p test1234 protected-file.7z"
  show "  Show content of password protected file" $DARK
  show ""
}

# Show info about version
#
# Code: No
# Echo: No
about() {
  show ""
  show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} - Utility for output data in 7z archive to stdout"
  show ""
  show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
  show "Essential Kaos Open Source License <https://essentialkaos.com/ekol>" $DARK
  show ""
}

# Show warning message about unsupported argument
#
# 1: Argument name (String)
#
# Code: No
# Echo: No
showArgWarn() {
  error "Unknown argument $1" $RED
  exit 1
}

## ARGUMENTS PARSING 4 #################################################################

[[ $# -eq 0 ]] && main && exit $?

unset arg argn argm argv argt argk

argv="$*" ; argt=""

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$argn" ]] ; then
    declare "$argn=$1"

    unset argn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    argm=${1:1}

    if [[ \ $SHORT_ARGS\  =~ \ $argm:!?([a-zA-Z0-9_]*) ]] ; then
      arg="${BASH_REMATCH[1]}"
    else
      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
      shift && continue
    fi

    if [[ -z "$argn" ]] ; then
      argn=$arg
    else
      # shellcheck disable=SC2015
      [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
      argn=$arg
    fi

    if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$argn=true" ; unset argn ; argk=true
    else
      unset argk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    arg=${1:2}

    if [[ $arg == *=* ]] ; then
      IFS="=" read -ra arg <<< "$arg"

      argm="${arg[0]}" ; argm=${argm//-/_}

      if [[ ! $SUPPORTED_ARGS\  =~ $argm\  ]] ; then
        declare -F showArgWarn &>/dev/null && showArgWarn "--${arg[0]//_/-}"
        shift && continue
      fi

      # shellcheck disable=SC2015
      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[*]:1:99}" || declare "$argm=${arg[*]:1:99}"

      unset argm && shift && continue
    else
      # shellcheck disable=SC2178
      arg=${arg//-/_}

      if [[ -z "$argn" ]] ; then
        # shellcheck disable=SC2128
        argn=$arg
      else
        # shellcheck disable=SC2015
        [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
        # shellcheck disable=SC2128
        argn=$arg
      fi

      if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
        declare -F showArgWarn &>/dev/null && showArgWarn "--${argn//_/-}"
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$argn=true" ; unset argn ; argk=true
      else
        unset argk
      fi

      shift && continue
    fi
  else
    if [[ -n "$argn" ]] ; then
      # shellcheck disable=SC2015
      [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"

      unset argn && shift && continue
    fi
  fi

  argt="$argt $1" ; shift

done

[[ -n "$argn" ]] && declare "$argn=true"

unset arg argn argm argk

# shellcheck disable=SC2015,SC2086
[[ -n "$KEEP_ARGS" ]] && main $argv || main ${argt:1}

########################################################################################
