#!/usr/bin/env bash

########################################################################################

APP="7zcat"
VER="1.2.0"

########################################################################################

NORM=0
BOLD=1
UNLN=4
RED=31
GREEN=32
BROWN=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[${NORM}m"
CL_BOLD="\e[${BOLD}m"
CL_UNLN="\e[${UNLN}m"
CL_RED="\e[${RED}m"
CL_GREEN="\e[${GREEN}m"
CL_BROWN="\e[${BROWN}m"
CL_BLUE="\e[${BLUE}m"
CL_MAG="\e[${MAG}m"
CL_CYAN="\e[${CYAN}m"
CL_GREY="\e[${GREY}m"
CL_DARK="\e[${DARK}m"
CL_BL_RED="\e[${RED};1m"
CL_BL_GREEN="\e[${GREEN};1m"
CL_BL_BROWN="\e[${BROWN};1m"
CL_BL_BLUE="\e[${BLUE};1m"
CL_BL_MAG="\e[${MAG};1m"
CL_BL_CYAN="\e[${CYAN};1m"
CL_BL_GREY="\e[${GREY};1m"
CL_BL_DARK="\e[${DARK};1m"
CL_UL_RED="\e[${RED};4m"
CL_UL_GREEN="\e[${GREEN};4m"
CL_UL_BROWN="\e[${BROWN};4m"
CL_UL_BLUE="\e[${BLUE};4m"
CL_UL_MAG="\e[${MAG};4m"
CL_UL_CYAN="\e[${CYAN};4m"
CL_UL_GREY="\e[${GREY};4m"
CL_UL_DARK="\e[${DARK};4m"
CL_BG_RED="\e[${RED};7m"
CL_BG_GREEN="\e[${GREEN};7m"
CL_BG_BROWN="\e[${BROWN};7m"
CL_BG_BLUE="\e[${BLUE};7m"
CL_BG_MAG="\e[${MAG};7m"
CL_BG_CYAN="\e[${CYAN};7m"
CL_BG_GREY="\e[${GREY};7m"
CL_BG_DARK="\e[${DARK};7m"

########################################################################################

SUPPORTED_ARGS="pass password !no_colors !help !usage !version !ver"
SHORT_ARGS="p:password nc:!no_colors h:!help v:!version"

########################################################################################

main() {
  if [[ ! -t 1 || -n "$no_colors" ]] ; then
    unset NORM BOLD UNLN RED GREEN BROWN BLUE MAG CYAN GREY DARK
    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_BROWN CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
    unset CL_BL_RED CL_BL_GREEN CL_BL_BROWN CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_BL_DARK
    unset CL_UL_RED CL_UL_GREEN CL_UL_BROWN CL_UL_BLUE CL_UL_MAG CL_UL_CYAN CL_UL_GREY CL_UL_DARK
    unset CL_BG_RED CL_BG_GREEN CL_BG_BROWN CL_BG_BLUE CL_BG_MAG CL_BG_CYAN CL_BG_GREY CL_BG_DARK
  fi

  if [[ -n "$ver" || -n "$version" ]] ; then
    about
    exit 0
  fi

  if [[ -n "$help" || -n "$usage" || $# -eq 0 ]] ; then
    usage
    exit 0
  fi

  if [[ ! $(type -P 7za) ]] ; then
    show "Error! 7zip not installed." $RED
    exit 1
  fi

  [[ -n "$pass" ]] && password="$pass"
  [[ "$password" == "true" ]] && readUserPassword

  local file file_name

  for file in "$@" ; do
    file_name=$(basename "$file")

    if [[ ! -f $file ]] ; then
      show "Error! $file_name is not a file." $RED
      continue
    elif [[ ! -r $file ]]; then
      show "Error! $file_name is not a readable file." $RED
      continue
    fi

    if ! is7zArch "$file" ; then
      show "Error! $file_name is not a 7z archive." $RED
      continue
    fi

    if isProtectedArch "$file" && [[ -z "$password" ]] ; then
      readUserPassword "$file"
    fi

    if [[ -n "$password" ]] ; then
      7za e -p"${password}" -so -bd "$file" 2> /dev/null

      if [[ $? -eq 2 ]] ; then
        show "Error! Wrong password." $RED
      fi
    else
      7za e -so -bd "$file" 2> /dev/null
    fi
  done
}

# Read password
#
# 1: Path to file (String)
#
# Code: No
# Echo: No
readUserPassword() {
  local file_name=$(basename "$1")

  while : ; do
    if [[ -n "$file_name" ]] ; then
      show "Please enter password for $file_name:" $CYAN
    else
      show "Please enter password:" $CYAN
    fi

    read -e -p -r "> " user_pass

    clnPassInput ${#user_pass}

    show ""

    if [[ -z "$user_pass" ]] ; then
      show "Password can't be empty." $BROWN
    else
      password="$user_pass"
      break
    fi
  done
}

# Check if given file is 7z archive
#
# 1: Path to file (String)
#
# Code: Yes
# Echo: No
is7zArch() {
  7za l "$1" &> /dev/null
  return $?
}

# Check if archive use password protection
#
# 1: Path to file (String)
#
# Code: Yes
# Echo: No
isProtectedArch() {
  if [[ $(7za l "$1" | grep "7zAES") != "" ]] ; then
    return 0
  else
    return 1
  fi
}

# Replace entered password by masking symbols
#
# Code: No
# Echo: No
clnPassInput() {
  local i result

  result="${result}> "

  for i in $(seq 1 "$1") ; do
    result="${result}*"
  done

  printf "\e[1A%s\n" "$result"
}

########################################################################################

# Show message
#
# 1: Message (String)
# 2: Message color (Number) [Optional]
#
# Code: No
# Echo: No
show() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

# Print usage info
#
# Code: No
# Echo: No
usage() {
  show ""
  show "${CL_BOLD}Usage:${CL_NORM} 7zcat ${CL_GREEN}{options}${CL_NORM} file..."
  show ""
  show "Options" $BOLD
  show ""
  if [[ -n "$DARK" ]] ; then
    show "  ${CL_GREEN}--password, -p${CL_NORM} ${CL_GREY}password${CL_NORM} ${CL_DARK}..${CL_NORM} Use password for unpacking archives"
    show "  ${CL_GREEN}--no-color, -nc${CL_NORM} ${CL_DARK}..........${CL_NORM} Disable colors in output"
    show "  ${CL_GREEN}--help, -h${CL_NORM} ${CL_DARK}...............${CL_NORM} Show this help message"
    show "  ${CL_GREEN}--version, -v${CL_NORM} ${CL_DARK}............${CL_NORM} Show information about version"
  else
    show "  ${CL_GREEN}--password, -p${CL_NORM} ${CL_GREY}password${CL_NORM}    Use password for unpacking archives"
    show "  ${CL_GREEN}--no-color, -nc${CL_NORM}            Disable colors in output"
    show "  ${CL_GREEN}--help, -h${CL_NORM}                 Show this help message"
    show "  ${CL_GREEN}--version, -v${CL_NORM}              Show information about version"
  fi
  show ""
  show "Examples" $BOLD
  show ""
  show "  7zcat file.7z"
  show "  Show content of file.7z" $DARK
  show ""
  show "  7zcat -p test1234 protected-file.7z"
  show "  Show content of password protected file" $DARK
  show ""
}

about() {
  show ""
  show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} - Utility for output data in 7z archive to stdout"
  show ""
  show "Copyright (C) 2009-2016 ESSENTIAL KAOS" $DARK
  show "Essential Kaos Open Source License <http://essentialkaos.com/ekol>" $DARK
  show ""
}

showArgWarn() {
  show "Unknown argument $1." $RED
  exit 1
}

## ARGUMENTS PARSING 2 #################################################################

[[ $# -eq 0 ]] && main && exit $?

unset arg argn argm argv argt argk

argv="$*" ; argt=""

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$argn" ]] ; then
    declare "$argn=$1"

    unset argn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    argm=${1:1}

    if [[ \ $SHORT_ARGS\  =~ \ $argm:!?([a-zA-Z0-9_]*) ]] ; then
      arg="${BASH_REMATCH[1]}"
    else
      showArgWarn "-$argm" 2> /dev/null || :
      shift && continue
    fi

    if [[ -z "$argn" ]] ; then
      argn=$arg
    else
      [[ -z "$argk" ]] && ( showArgValWarn "--$argn" 2> /dev/null || : ) || declare "$argn=true"
      argn=$arg
    fi

    if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
      showArgWarn "-$argm" 2> /dev/null || :
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$argn=true" ; unset argn ; argk=true
    else
      unset argk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    arg=${1:2}

    if [[ $arg == *=* ]] ; then
      IFS="=" read -ra arg <<< "$arg"

      argm="${arg[0]}" ; argm=${argm//-/_}

      if [[ ! $SUPPORTED_ARGS\  =~ $argm\  ]] ; then
        showArgWarn "--${arg[0]//_/-}" 2> /dev/null || :
        shift && continue
      fi

      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[@]:1:99}" || declare "$argm=${arg[@]:1:99}"

      unset argm && shift && continue
    else
      arg=${arg//-/_}

      if [[ -z "$argn" ]] ; then
        argn=$arg
      else
        [[ -z "$argk" ]] && ( showArgValWarn "--$argn" 2> /dev/null || : ) || declare "$argn=true"
        argn=$arg
      fi

      if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
        showArgWarn "--${argn//_/-}" 2> /dev/null || :
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$argn=true" ; unset argn ; argk=true
      else
        unset argk
      fi

      shift && continue
    fi
  else
    if [[ -n "$argn" ]] ; then
      [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"

      unset argn && shift && continue
    fi
  fi

  argt="$argt $1" ; shift

done

[[ -n "$argn" ]] && declare "$argn=true"

unset arg argn argm argk

[[ -n "$KEEP_ARGS" ]] && main $argv || main ${argt:1:9999}

########################################################################################
