name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Bibop:
    name: Bibop
    runs-on: ubuntu-latest

    steps:
      - name: Install p7zip
        run: sudo apt-get install -y -qq p7zip-full

      - name: Print p7zip version
        run: 7za -h

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run test recipes with Bibop
        uses: essentialkaos/bibop-action@v1
        with:
          recipe: .bibop/7zcat.recipe
          path: SOURCES

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check specs with Perfecto
        uses: essentialkaos/perfecto-action@v2
        with:
          files: 7zcat.spec

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: SOURCES/7zcat

  Typos:
    name: Typos
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master
